blank_issues_enabled: false

contact_links:
  - name: GitHub Issues
    url: https://github.com/github-trending-analyzer/issues

templates:
  - name: "Feature Request"
    filename: "feature_request.md"
  - name: "Bug Report"
    filename: "bug_report.md"